const lib = require('./lib');
module.exports = {
  ...lib.myfunc,
  ...lib.color,
  ...lib.converter,
  ...lib.exif,
  ...lib.remini,
  ...lib.catbox,
  ...lib.event,
  ...lib.scraper,
  PluginManager: lib.PluginManager,
  makeInMemoryStore: lib.store.makeInMemoryStore,
  ObjectRepository: lib.store.ObjectRepository,
  makeOrderedDictionary: lib.store.makeOrderedDictionary,
  utils: lib.myfunc,
  colors: lib.color,
  media: {
    ...lib.converter,
    ...lib.exif,
    ...lib.remini,
    ...lib.catbox
  },
  scrapers: lib.scraper,
  events: lib.event,
  store: lib.store,
  convertToAudio: lib.converter.toAudio,
  convertToPTT: lib.converter.toPTT,
  convertToVideo: lib.converter.toVideo,
  enhanceImage: lib.remini.remini,
  imageToWebp: lib.exif.imageToWebp,
  videoToWebp: lib.exif.videoToWebp,
  addStickerMetadata: lib.exif.addExif,
  downloadBuffer: lib.myfunc.getBuffer,
  uploadToCatbox: lib.catbox.handleMediaUpload,
  serializeMessage: lib.myfunc.smsg,
  formatFileSize: lib.myfunc.formatSize,
  formatUptime: lib.myfunc.runtime,
  styleText: lib.scraper.styletext,
  formatDate: lib.myfunc.formatDate,
  getFormattedTime: lib.myfunc.getTime,
  getGroupAdmins: lib.myfunc.getGroupAdmins,
  parseMentions: lib.myfunc.parseMention,
  createStore: lib.store.makeInMemoryStore
};